version: "3.9"

services:
  php:
    build: ./docker/php
    container_name: lotus-php
    volumes:
      - ./backend:/var/www
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.27-alpine
    container_name: lotus-nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: mariadb:11
    container_name: lotus-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306" # ローカルから繋ぐ用（必要なら）

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: lotus-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - "8081:80"
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: lotus-redis
    ports:
      - "6379:6379"

volumes:
  db_data:
